import React, { useMemo, useState } from 'react';
import { SafeAreaView, ScrollView, View, Text, TextInput, Pressable, StyleSheet, KeyboardAvoidingView, Platform } from 'react-native';
import { StatusBar } from 'expo-status-bar';

const C={bg:'#F7F5EF',text:'#23362F',muted:'#6D7C75',green:'#355E50',line:'#D8DDD8',card:'#ECEFEA',white:'#FFFFFF'};
const initial={family:'',friends:'',work:'',self:'',essence:'',vision:'',belief:'',counter:'',newBelief:'',focusIssue:'',focusNext:''};

export default function App(){
 const [step,setStep]=useState(0); const [a,setA]=useState(initial); const [msg,setMsg]=useState('');
 const total=13; const set=(k,v)=>setA(x=>({...x,[k]:v}));
 const required={2:'family',3:'friends',4:'work',5:'self',6:'essence',7:'vision',8:'belief',9:'counter',10:'focusIssue'};
 const next=()=>{const key=required[step]; if(key&&!a[key].trim()){setMsg('Schreib zuerst auf, was dir dazu durch den Kopf geht.');return;} if(step===9&&!a.newBelief.trim()){setMsg('Formuliere zuerst den Satz, den du mitnehmen möchtest.');return;} if(step===10&&!a.focusNext.trim()){setMsg('Formuliere zuerst, worauf du deine Energie richten möchtest.');return;} setMsg('');setStep(s=>Math.min(s+1,total-1));};
 const progress=useMemo(()=>`${Math.round(((step+1)/total)*100)}%`,[step]);
 const input=(key,placeholder)=> <TextInput value={a[key]} onChangeText={v=>set(key,v)} placeholder={placeholder} placeholderTextColor="#98A29D" multiline textAlignVertical="top" style={styles.input}/>;
 const Button=({title='Weiter',onPress=next,outline=false})=><Pressable onPress={onPress} style={({pressed})=>[styles.button,outline&&styles.buttonOutline,pressed&&{opacity:.78}]}><Text style={[styles.buttonText,outline&&{color:C.green}]}>{title}</Text></Pressable>;
 const Eyebrow=({children})=><Text style={styles.eyebrow}>{children}</Text>;
 const Horizon=()=> <View style={styles.horizon}><View style={styles.mountainA}/><View style={styles.mountainB}/><View style={styles.lake}/></View>;
 const Review=()=> <View style={{gap:10}}>{[['Familie',a.family],['Freundschaft',a.friends],['Dein Wirken',a.work],['Dein Blick',a.self]].map(([l,v])=><View style={styles.review} key={l}><Text style={styles.reviewLabel}>{l}</Text><Text style={styles.body}>{v}</Text></View>)}</View>;
 let body;
 if(step===0) body=<><Horizon/><Text style={styles.hero}>Finde heraus, was dich leitet.</Text><Text style={styles.body}>Manche Antworten tragen wir längst in uns. Wir nehmen uns nur selten die Zeit, die richtigen Fragen zu stellen.\n\nPLORANA gibt dir diesen Raum. Du denkst nach, schreibst auf und findest heraus, was für dich zählt.</Text><Button title="Los geht’s"/></>;
 if(step===1) body=<><View style={styles.scene}><Eyebrow>EINE REISE IN DIE ZUKUNFT</Eyebrow><Text style={styles.hero}>Stell dir deinen 80. Geburtstag vor.</Text><Horizon/><Text style={styles.body}>Wo feierst du? Wer ist bei dir? Wie sieht dieser Tag aus?\n\nNimm dir einen Moment und lass das Bild entstehen. Vielleicht siehst du einen Ort vor dir oder einzelne Menschen. Vielleicht weißt du sofort, wie sich dieser Tag anfühlt.\n\nWenn du dort angekommen bist, schauen wir gemeinsam zurück.</Text></View><Button title="Ich bin soweit"/></>;
 if(step===2) body=<><Eyebrow>FAMILIE</Eyebrow><Text style={styles.title}>Ein Mensch aus deiner Familie erzählt von dir.</Text><Text style={styles.body}>Was soll er über dich als Menschen sagen können, wenn er auf euer gemeinsames Leben zurückblickt?</Text>{input('family','Schreib auf, was dir in den Sinn kommt …')}<Button/></>;
 if(step===3) body=<><Eyebrow>FREUNDSCHAFT</Eyebrow><Text style={styles.title}>Jetzt hörst du deinen Freunden zu.</Text><Text style={styles.body}>Wenn sie von den Jahren mit dir erzählen, wofür sollen sie dich geschätzt haben?</Text>{input('friends','Für …')}<Button/></>;
 if(step===4) body=<><Eyebrow>DEIN WIRKEN</Eyebrow><Text style={styles.title}>Auch Menschen, mit denen du gearbeitet hast, erinnern sich.</Text><Text style={styles.body}>Was sollen sie über die Zeit mit dir erzählen und darüber, was durch dich entstanden ist?</Text>{input('work','Ich wünsche mir, dass …')}<Button/></>;
 if(step===5) body=<><Eyebrow>DEIN BLICK</Eyebrow><Text style={styles.title}>Jetzt werden die anderen Stimmen leiser.</Text><Text style={styles.body}>Du blickst selbst auf dein Leben zurück. Was möchtest du über den Menschen sagen können, der du geworden bist?</Text>{input('self','Wenn ich zurückblicke …')}<Button title="Meine Gedanken ansehen"/></>;
 if(step===6) body=<><Eyebrow>VERDICHTEN</Eyebrow><Text style={styles.title}>Schau noch einmal auf deine eigenen Worte.</Text><Text style={styles.body}>Welche Gedanken tauchen immer wieder auf? Vielleicht stehen dort unterschiedliche Sätze, die im Kern dasselbe meinen. Was davon möchtest du auf keinen Fall aus den Augen verlieren?</Text><Review/>{input('essence','Wenn ich es auf den Kern bringe …')}<Button/></>;
 if(step===7) body=<><Eyebrow>VOM BILD IN DEN ALLTAG</Eyebrow><Text style={styles.title}>Stell dir jetzt einen ganz gewöhnlichen Tag in diesem Leben vor.</Text><Text style={styles.body}>Vielleicht ist es ein Dienstag irgendwann auf dem Weg zu deinem 80. Geburtstag. Woran würdest du merken, dass die Dinge, die dir gerade wichtig geworden sind, in deinem Alltag tatsächlich einen Platz haben?</Text>{input('vision','An diesem Tag würde ich …')}<Button/></>;
 if(step===8) body=<><Eyebrow>GLAUBENSSÄTZE</Eyebrow><Text style={styles.title}>Und was macht es dir manchmal schwer, genau so zu leben?</Text><Text style={styles.body}>Achte auf den Satz, der dabei in deinem Kopf auftaucht. Was glaubst du in solchen Momenten über dich, über andere oder darüber, wie das Leben funktioniert?</Text>{input('belief','Ein Satz, der mir dabei begegnet, ist …')}<Button title="Den Gedanken genauer ansehen"/></>;
 if(step===9) body=<><View style={styles.card}><Eyebrow>DEIN GEDANKE</Eyebrow><Text style={styles.body}>{a.belief}</Text></View><Text style={styles.title}>Wie wahr ist dieser Satz eigentlich?</Text><Text style={styles.body}>Denk an Situationen, in denen er nicht gestimmt hat. Was spricht gegen ihn oder macht ihn zumindest weniger eindeutig?</Text>{input('counter','Anders war es zum Beispiel, als …')}<Text style={styles.label}>Welcher Satz würde deiner Erfahrung besser gerecht und dir gleichzeitig mehr Handlungsspielraum lassen?</Text>{input('newBelief','Ich möchte mich daran erinnern, dass …')}<Button title="Diesen Satz mitnehmen"/></>;
 if(step===10) body=<><Eyebrow>DEIN WIRKUNGSRAUM</Eyebrow><Text style={styles.title}>Wohin geht deine Aufmerksamkeit gerade?</Text><Text style={styles.body}>Denk an etwas, das dich im Moment beschäftigt. Was daran liegt wirklich in deiner Hand und wo kreisen deine Gedanken um etwas, das du kaum beeinflussen kannst?</Text>{input('focusIssue','Meine Aufmerksamkeit hängt gerade an …')}<Text style={styles.label}>Wenn du deine Energie bewusst einsetzen könntest, worauf möchtest du deinen Fokus richten?</Text>{input('focusNext','Ich möchte meine Energie stärker darauf richten …')}<Button/></>;
 if(step===11) body=<><Horizon/><Text style={styles.hero}>Deine erste Map entsteht.</Text><Text style={styles.body}>Du hast gerade aus verschiedenen Perspektiven auf dein Leben geschaut und dabei Gedanken festgehalten, die im Alltag leicht untergehen.\n\nEinige davon werden sich verändern, während andere dich vielleicht lange begleiten. Mit jeder weiteren Reflexion kann deutlicher werden, was dir wichtig ist und woran du dich orientieren möchtest.\n\nDeine Map soll dich dabei nicht festlegen. Sie gibt dir etwas, zu dem du zurückkehren kannst, wenn du dich fragst, ob das Leben, das du gerade führst, noch zu dem passt, was dich leitet.</Text><Button title="Meine Map ansehen"/></>;
 if(step===12) body=<><Eyebrow>DEINE MAP</Eyebrow><Text style={styles.title}>Was du heute über dich herausgefunden hast</Text><View style={styles.card}><Eyebrow>WAS MIR WICHTIG IST</Eyebrow><Text style={styles.body}>{a.essence||'Noch offen'}</Text></View><View style={styles.card}><Eyebrow>WORAN ICH MICH ERINNERN MÖCHTE</Eyebrow><Text style={styles.body}>{a.newBelief||'Noch offen'}</Text></View><View style={styles.card}><Eyebrow>WORAUF ICH MEINE ENERGIE RICHTEN MÖCHTE</Eyebrow><Text style={styles.body}>{a.focusNext||'Noch offen'}</Text></View><Button title="Noch einmal durchgehen" outline onPress={()=>{setA(initial);setStep(0);setMsg('')}}/></>;
 return <SafeAreaView style={styles.safe}><StatusBar style="dark"/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><View style={styles.top}><Text style={styles.brand}>PLORANA</Text><Text style={styles.count}>{step?`${step} / ${total-1}`:''}</Text></View><View style={styles.track}><View style={[styles.fill,{width:progress}]}/></View>{body}{!!msg&&<Text style={styles.msg}>{msg}</Text>}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},page:{paddingHorizontal:22,paddingTop:14,paddingBottom:52},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:16},brand:{fontSize:14,letterSpacing:4,color:C.text,fontWeight:'600'},count:{fontSize:12,color:C.muted},track:{height:3,backgroundColor:C.line,borderRadius:20,overflow:'hidden',marginBottom:34},fill:{height:3,backgroundColor:C.green},hero:{fontSize:34,lineHeight:41,color:C.text,fontWeight:'500',marginBottom:18},title:{fontSize:27,lineHeight:34,color:C.text,fontWeight:'500',marginBottom:14},body:{fontSize:17,lineHeight:27,color:C.text},eyebrow:{fontSize:11,letterSpacing:2,color:C.muted,fontWeight:'600',marginBottom:12},input:{minHeight:150,borderWidth:1,borderColor:C.line,borderRadius:16,padding:16,fontSize:17,lineHeight:25,color:C.text,backgroundColor:'rgba(255,255,255,.28)',marginTop:20},button:{backgroundColor:C.green,borderRadius:15,paddingVertical:14,paddingHorizontal:18,alignItems:'center',marginTop:22,borderWidth:1,borderColor:C.green},buttonOutline:{backgroundColor:'transparent'},buttonText:{fontSize:16,color:C.white,fontWeight:'600'},msg:{fontSize:14,lineHeight:21,color:C.muted,marginTop:14},scene:{borderWidth:1,borderColor:C.line,borderRadius:24,padding:22,backgroundColor:C.card},horizon:{height:132,borderRadius:20,overflow:'hidden',backgroundColor:'#E8ECE8',marginBottom:26,position:'relative'},mountainA:{position:'absolute',width:250,height:150,backgroundColor:'#C6D0CA',transform:[{rotate:'38deg'}],left:-80,top:55},mountainB:{position:'absolute',width:280,height:170,backgroundColor:'#B7C4BD',transform:[{rotate:'-36deg'}],right:-105,top:54},lake:{position:'absolute',left:0,right:0,bottom:0,height:38,backgroundColor:'#D7E0DD'},review:{borderWidth:1,borderColor:C.line,borderRadius:14,padding:15},reviewLabel:{fontSize:11,color:C.muted,marginBottom:5,textTransform:'uppercase',letterSpacing:1.2},card:{backgroundColor:C.card,borderRadius:16,padding:18,marginTop:14},label:{fontSize:16,lineHeight:24,color:C.text,fontWeight:'600',marginTop:24}});
