import React, { useEffect, useMemo, useState } from 'react';
import { SafeAreaView, ScrollView, View, Text, TextInput, Pressable, StyleSheet, KeyboardAvoidingView, Platform, Alert, Image } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import AsyncStorage from '@react-native-async-storage/async-storage';

const C={bg:'#F7F5EF',text:'#21352E',muted:'#6D7C75',green:'#355E50',green2:'#577A6C',line:'#D8DDD8',card:'#ECEFEA',white:'#FFFFFF',sand:'#E7E1D5',sky:'#DDE7E3'};
const STORAGE_KEY='plorana.v1';
const initial={family:'',friends:'',work:'',self:'',essence:'',vision:'',belief:'',counter:'',newBelief:'',focusIssue:'',focusNext:''};
const menuItems=[['home','Start'],['reflect','Reflexionen'],['map','Meine Map'],['settings','Einstellungen'],['legal','Über PLORANA & Rechtliches']];

export default function App(){
 const [screen,setScreen]=useState('home');
 const [step,setStep]=useState(1);
 const [a,setA]=useState(initial);
 const [msg,setMsg]=useState('');
 const [menuOpen,setMenuOpen]=useState(false);
 const [loaded,setLoaded]=useState(false);
 const total=12;

 useEffect(()=>{(async()=>{try{const raw=await AsyncStorage.getItem(STORAGE_KEY);if(raw)setA({...initial,...JSON.parse(raw)});}catch(e){}finally{setLoaded(true)}})()},[]);
 useEffect(()=>{if(loaded)AsyncStorage.setItem(STORAGE_KEY,JSON.stringify(a)).catch(()=>{});},[a,loaded]);
 const set=(k,v)=>setA(x=>({...x,[k]:v}));
 const required={2:'family',3:'friends',4:'work',5:'self',6:'essence',7:'vision',8:'belief',9:'counter',10:'focusIssue'};
 const next=()=>{const key=required[step];if(key&&!a[key].trim()){setMsg('Schreib zuerst auf, was dir dazu durch den Kopf geht.');return;}if(step===9&&!a.newBelief.trim()){setMsg('Formuliere zuerst den Satz, den du mitnehmen möchtest.');return;}if(step===10&&!a.focusNext.trim()){setMsg('Formuliere zuerst, worauf du deine Energie richten möchtest.');return;}setMsg('');setStep(s=>Math.min(s+1,total));};
 const progress=useMemo(()=>`${Math.round((step/total)*100)}%`,[step]);
 const input=(key,placeholder)=><TextInput value={a[key]} onChangeText={v=>set(key,v)} placeholder={placeholder} placeholderTextColor="#98A29D" multiline textAlignVertical="top" style={styles.input}/>;
 const Button=({title='Weiter',onPress=next,outline=false})=><Pressable onPress={onPress} style={({pressed})=>[styles.button,outline&&styles.buttonOutline,pressed&&{opacity:.78}]}><Text style={[styles.buttonText,outline&&{color:C.green}]}>{title}</Text></Pressable>;
 const Eyebrow=({children})=><Text style={styles.eyebrow}>{children}</Text>;

 const go=(s)=>{setMenuOpen(false);setScreen(s);};
 const startReflection=()=>{setStep(1);setMsg('');setScreen('reflect');};
 const clearData=()=>{const run=async()=>{setA(initial);await AsyncStorage.removeItem(STORAGE_KEY).catch(()=>{});setStep(1);setScreen('home');};if(Platform.OS==='web'){if(typeof window!=='undefined'&&window.confirm('Möchtest du deine lokal gespeicherten Reflexionen wirklich löschen?'))run();}else Alert.alert('Meine Daten löschen','Alle lokal gespeicherten Reflexionen auf diesem Gerät werden gelöscht.',[{text:'Abbrechen',style:'cancel'},{text:'Löschen',style:'destructive',onPress:run}]);};

 const Landscape=({large=false})=><View style={[styles.landscape,large&&styles.landscapeLarge]} accessibilityLabel="Ruhige Berglandschaft am See">
   <Image source={require('./assets/plorana-hero.jpg')} resizeMode="cover" style={styles.landscapeImage}/>
   <View style={styles.landscapeVeil}/>
 </View>;
 const Review=()=> <View style={{gap:10}}>{[['Familie',a.family],['Freundschaft',a.friends],['Dein Wirken',a.work],['Dein Blick',a.self]].map(([l,v])=><View style={styles.review} key={l}><Text style={styles.reviewLabel}>{l}</Text><Text style={styles.body}>{v}</Text></View>)}</View>;

 const Header=({flow=false})=><><View style={styles.top}><Pressable onPress={()=>go('home')}><Text style={styles.brand}>PLORANA</Text></Pressable><View style={styles.headerRight}>{flow&&<Text style={styles.count}>{step} / {total}</Text>}<Pressable accessibilityLabel="Menü öffnen" onPress={()=>setMenuOpen(true)} style={styles.menuButton}><Text style={styles.menuGlyph}>☰</Text></Pressable></View></View>{flow&&<View style={styles.track}><View style={[styles.fill,{width:progress}]}/></View>}</>;

 const Menu=()=> menuOpen?<View style={styles.menuOverlay}><SafeAreaView style={styles.menuPanel}><View style={styles.menuHead}><Text style={styles.brand}>PLORANA</Text><Pressable onPress={()=>setMenuOpen(false)} style={styles.closeButton}><Text style={styles.closeGlyph}>×</Text></Pressable></View><Text style={styles.menuTitle}>Menü</Text>{menuItems.map(([id,label])=><Pressable key={id} onPress={()=>go(id)} style={styles.menuRow}><Text style={styles.menuRowText}>{label}</Text><Text style={styles.chev}>›</Text></Pressable>)}<View style={styles.menuFoot}><Text style={styles.small}>PLORANA · Testversion 1.0</Text></View></SafeAreaView></View>:null;

 let body;
 if(screen==='home') body=<><View style={styles.homeTop}><Text style={styles.brand}>PLORANA</Text><Pressable accessibilityLabel="Menü öffnen" onPress={()=>setMenuOpen(true)} style={styles.menuButton}><Text style={styles.menuGlyph}>☰</Text></Pressable></View><Landscape large/><Eyebrow>DEIN RAUM ZUM NACHDENKEN</Eyebrow><Text style={styles.homeHero}>Finde heraus, was dich leitet.</Text><Text style={styles.body}>Manche Antworten tragen wir längst in uns. Wir nehmen uns nur selten die Zeit, die richtigen Fragen zu stellen.</Text><Text style={[styles.body,styles.paragraph]}>PLORANA gibt dir diesen Raum. Du denkst nach, schreibst auf und findest heraus, was für dich zählt.</Text><Button title="Los geht’s" onPress={startReflection}/><View style={styles.quickGrid}><Pressable style={styles.quickCard} onPress={()=>go('map')}><Text style={styles.quickKicker}>DEINE ORIENTIERUNG</Text><Text style={styles.quickTitle}>Meine Map</Text><Text style={styles.quickArrow}>↗</Text></Pressable><Pressable style={styles.quickCard} onPress={startReflection}><Text style={styles.quickKicker}>WEITERDENKEN</Text><Text style={styles.quickTitle}>Reflexionen</Text><Text style={styles.quickArrow}>↗</Text></Pressable><Pressable style={styles.quickCard} onPress={()=>go('settings')}><Text style={styles.quickKicker}>PRIVAT & LOKAL</Text><Text style={styles.quickTitle}>Einstellungen</Text><Text style={styles.quickArrow}>↗</Text></Pressable><Pressable style={styles.quickCard} onPress={()=>go('legal')}><Text style={styles.quickKicker}>TRANSPARENT</Text><Text style={styles.quickTitle}>Rechtliches</Text><Text style={styles.quickArrow}>↗</Text></Pressable></View></>;

 if(screen==='reflect'){
  let flow;
  if(step===1) flow=<><View style={styles.scene}><Eyebrow>EINE REISE IN DIE ZUKUNFT</Eyebrow><Text style={styles.hero}>Stell dir deinen 80. Geburtstag vor.</Text><Landscape/><Text style={styles.body}>Wo feierst du? Wer ist bei dir? Wie sieht dieser Tag aus?</Text><Text style={[styles.body,styles.paragraph]}>Nimm dir einen Moment und lass das Bild entstehen. Vielleicht siehst du einen Ort vor dir oder einzelne Menschen. Vielleicht weißt du sofort, wie sich dieser Tag anfühlt.</Text><Text style={[styles.body,styles.paragraph]}>Wenn du dort angekommen bist, schauen wir gemeinsam zurück.</Text></View><Button title="Ich bin soweit"/> </>;
  if(step===2) flow=<><Eyebrow>FAMILIE</Eyebrow><Text style={styles.title}>Ein Mensch aus deiner Familie erzählt von dir.</Text><Text style={styles.body}>Was soll er über dich als Menschen sagen können, wenn er auf euer gemeinsames Leben zurückblickt?</Text>{input('family','Schreib auf, was dir in den Sinn kommt …')}<Button/></>;
  if(step===3) flow=<><Eyebrow>FREUNDSCHAFT</Eyebrow><Text style={styles.title}>Jetzt hörst du deinen Freunden zu.</Text><Text style={styles.body}>Wenn sie von den Jahren mit dir erzählen, wofür sollen sie dich geschätzt haben?</Text>{input('friends','Für …')}<Button/></>;
  if(step===4) flow=<><Eyebrow>DEIN WIRKEN</Eyebrow><Text style={styles.title}>Auch Menschen, mit denen du gearbeitet hast, erinnern sich.</Text><Text style={styles.body}>Was sollen sie über die Zeit mit dir erzählen und darüber, was durch dich entstanden ist?</Text>{input('work','Ich wünsche mir, dass …')}<Button/></>;
  if(step===5) flow=<><Eyebrow>DEIN BLICK</Eyebrow><Text style={styles.title}>Jetzt werden die anderen Stimmen leiser.</Text><Text style={styles.body}>Du blickst selbst auf dein Leben zurück. Was möchtest du über den Menschen sagen können, der du geworden bist?</Text>{input('self','Wenn ich zurückblicke …')}<Button title="Meine Gedanken ansehen"/></>;
  if(step===6) flow=<><Eyebrow>VERDICHTEN</Eyebrow><Text style={styles.title}>Schau noch einmal auf deine eigenen Worte.</Text><Text style={styles.body}>Welche Gedanken tauchen immer wieder auf? Vielleicht stehen dort unterschiedliche Sätze, die im Kern dasselbe meinen. Was davon möchtest du auf keinen Fall aus den Augen verlieren?</Text><Review/>{input('essence','Wenn ich es auf den Kern bringe …')}<Button/></>;
  if(step===7) flow=<><Eyebrow>VOM BILD IN DEN ALLTAG</Eyebrow><Text style={styles.title}>Stell dir jetzt einen ganz gewöhnlichen Tag in diesem Leben vor.</Text><Text style={styles.body}>Vielleicht ist es ein Dienstag irgendwann auf dem Weg zu deinem 80. Geburtstag. Woran würdest du merken, dass die Dinge, die dir gerade wichtig geworden sind, in deinem Alltag tatsächlich einen Platz haben?</Text>{input('vision','An diesem Tag würde ich …')}<Button/></>;
  if(step===8) flow=<><Eyebrow>GLAUBENSSÄTZE</Eyebrow><Text style={styles.title}>Und was macht es dir manchmal schwer, genau so zu leben?</Text><Text style={styles.body}>Achte auf den Satz, der dabei in deinem Kopf auftaucht. Was glaubst du in solchen Momenten über dich, über andere oder darüber, wie das Leben funktioniert?</Text>{input('belief','Ein Satz, der mir dabei begegnet, ist …')}<Button title="Den Gedanken genauer ansehen"/></>;
  if(step===9) flow=<><View style={styles.card}><Eyebrow>DEIN GEDANKE</Eyebrow><Text style={styles.body}>{a.belief}</Text></View><Text style={styles.title}>Wie wahr ist dieser Satz eigentlich?</Text><Text style={styles.body}>Denk an Situationen, in denen er nicht gestimmt hat. Was spricht gegen ihn oder macht ihn zumindest weniger eindeutig?</Text>{input('counter','Anders war es zum Beispiel, als …')}<Text style={styles.label}>Welcher Satz würde deiner Erfahrung besser gerecht und dir gleichzeitig mehr Handlungsspielraum lassen?</Text>{input('newBelief','Ich möchte mich daran erinnern, dass …')}<Button title="Diesen Satz mitnehmen"/></>;
  if(step===10) flow=<><Eyebrow>DEIN WIRKUNGSRAUM</Eyebrow><Text style={styles.title}>Wohin geht deine Aufmerksamkeit gerade?</Text><Text style={styles.body}>Denk an etwas, das dich im Moment beschäftigt. Was daran liegt wirklich in deiner Hand und wo kreisen deine Gedanken um etwas, das du kaum beeinflussen kannst?</Text>{input('focusIssue','Meine Aufmerksamkeit hängt gerade an …')}<Text style={styles.label}>Wenn du deine Energie bewusst einsetzen könntest, worauf möchtest du deinen Fokus richten?</Text>{input('focusNext','Ich möchte meine Energie stärker darauf richten …')}<Button/></>;
  if(step===11) flow=<><Landscape/><Text style={styles.hero}>Deine erste Map entsteht.</Text><Text style={styles.body}>Du hast gerade aus verschiedenen Perspektiven auf dein Leben geschaut und dabei Gedanken festgehalten, die sonst leicht im Alltag untergehen.</Text><Text style={[styles.body,styles.paragraph]}>Einige davon werden sich verändern, andere werden dich vielleicht lange begleiten. Mit jeder weiteren Reflexion wird deutlicher, was dir wichtig ist und woran du dich orientieren möchtest.</Text><Text style={[styles.body,styles.paragraph]}>PLORANA sammelt diese Gedanken nicht, um dich festzulegen. Sie sollen dir helfen, dich selbst immer wieder zu fragen, ob das Leben, das du gerade führst, noch zu dem passt, was dich leitet.</Text><Button title="Meine Map ansehen"/></>;
  if(step===12) flow=<><Eyebrow>DEINE MAP</Eyebrow><Text style={styles.title}>Was du heute über dich herausgefunden hast</Text><MapCards/><Button title="Zur Startseite" outline onPress={()=>go('home')}/></>;
  body=<><Header flow/>{flow}{!!msg&&<Text style={styles.msg}>{msg}</Text>}</>;
 }

 function MapCards(){return <><View style={styles.card}><Eyebrow>WAS MIR WICHTIG IST</Eyebrow><Text style={styles.body}>{a.essence||'Hier entsteht dein persönlicher Kern, sobald du eine Reflexion abgeschlossen hast.'}</Text></View><View style={styles.card}><Eyebrow>WORAN ICH MICH ERINNERN MÖCHTE</Eyebrow><Text style={styles.body}>{a.newBelief||'Dein eigener Trainingssatz erscheint später hier.'}</Text></View><View style={styles.card}><Eyebrow>WORAUF ICH MEINE ENERGIE RICHTEN MÖCHTE</Eyebrow><Text style={styles.body}>{a.focusNext||'Dein gewählter Fokus erscheint später hier.'}</Text></View></>}

 if(screen==='map') body=<><Header/><Eyebrow>MEINE MAP</Eyebrow><Text style={styles.hero}>Was dich leitet.</Text><Text style={styles.body}>Deine Map wächst mit deinen Reflexionen. Sie fasst deine eigenen Gedanken zusammen, ohne dich festzulegen.</Text><MapCards/><Button title="Neue Reflexion" onPress={startReflection}/></>;
 if(screen==='settings') body=<><Header/><Eyebrow>EINSTELLUNGEN</Eyebrow><Text style={styles.hero}>Deine Daten gehören dir.</Text><View style={styles.infoCard}><Text style={styles.infoTitle}>Speicherung</Text><Text style={styles.body}>In dieser Testversion werden deine Reflexionsantworten lokal auf diesem Gerät gespeichert. Es gibt kein Benutzerkonto und keine Cloud-Synchronisation.</Text></View><Pressable style={styles.dangerRow} onPress={clearData}><Text style={styles.dangerText}>Meine lokalen Daten löschen</Text><Text style={styles.chev}>›</Text></Pressable><Text style={styles.small}>Eine spätere Premium-Version ist technisch vorgesehen. Käufe und Abonnements sind in dieser Testversion noch nicht aktiviert.</Text></>;
 if(screen==='legal') body=<><Header/><Eyebrow>ÜBER PLORANA & RECHTLICHES</Eyebrow><Text style={styles.hero}>Transparent von Anfang an.</Text><LegalRow title="Datenschutz" onPress={()=>go('privacy')}/><LegalRow title="Impressum" onPress={()=>go('imprint')}/><LegalRow title="Kontakt" onPress={()=>go('contact')}/><View style={styles.note}><Text style={styles.small}>Hinweis zur Testversion: Die Betreiberangaben und die öffentliche Datenschutz-URL müssen vor einer Store-Veröffentlichung final ergänzt werden.</Text></View></>;
 if(screen==='privacy') body=<><Header/><Eyebrow>DATENSCHUTZ</Eyebrow><Text style={styles.hero}>Datenschutzhinweise</Text><LegalText title="1. Verantwortliche Stelle">Vor Veröffentlichung ergänzen: vollständiger Name bzw. Unternehmensname, ladungsfähige Anschrift und öffentliche Kontakt-E-Mail-Adresse.</LegalText><LegalText title="2. Verarbeitung in der App">PLORANA verarbeitet die Texte, die du während deiner Reflexionen eingibst. In dieser Testversion werden diese Inhalte lokal auf deinem Gerät gespeichert. PLORANA übermittelt diese Reflexionsinhalte nicht an einen eigenen Server.</LegalText><LegalText title="3. Lokale Speicherung und Löschung">Die lokal gespeicherten Reflexionsdaten bleiben auf deinem Gerät, bis du sie in den Einstellungen löschst oder die App-Daten auf deinem Gerät entfernst. Unter „Einstellungen“ kannst du die in PLORANA gespeicherten Reflexionen löschen.</LegalText><LegalText title="4. Drittanbieter und technische Daten">Vor der Veröffentlichung wird die finale App einschließlich der eingesetzten Expo-, Apple- und Google-Komponenten darauf geprüft, ob technische oder personenbezogene Daten durch SDKs oder Store-Dienste verarbeitet werden. Diese Erklärung wird vor Veröffentlichung entsprechend ergänzt.</LegalText><LegalText title="5. Premium und Zahlungen">In der Testversion verarbeitet PLORANA keine Zahlungen. Wenn später kostenpflichtige digitale Funktionen angeboten werden, werden die tatsächlich eingesetzten Zahlungs- und Store-Dienste sowie die dabei verarbeiteten Daten hier beschrieben.</LegalText><Text style={styles.warning}>ENTWURF FÜR DIE TESTPHASE · Vor Veröffentlichung müssen Betreiberangaben, Rechtsgrundlagen, Empfänger, Speicherdauern, Betroffenenrechte und die finale technische Datenverarbeitung vollständig geprüft und ergänzt werden.</Text></>;
 if(screen==='imprint') body=<><Header/><Eyebrow>IMPRESSUM</Eyebrow><Text style={styles.hero}>Anbieterinformationen</Text><View style={styles.infoCard}><Text style={styles.body}>Angaben gemäß § 5 DDG</Text><Text style={[styles.body,styles.paragraph]}>[Vollständiger Name / Unternehmen]</Text><Text style={styles.body}>[Straße und Hausnummer]</Text><Text style={styles.body}>[PLZ und Ort]</Text><Text style={[styles.body,styles.paragraph]}>E-Mail: [öffentliche Kontaktadresse]</Text></View><Text style={styles.warning}>Vor einer öffentlichen kommerziellen Veröffentlichung müssen diese Platzhalter durch die tatsächlich erforderlichen Angaben ersetzt werden.</Text></>;
 if(screen==='contact') body=<><Header/><Eyebrow>KONTAKT</Eyebrow><Text style={styles.hero}>PLORANA erreichen.</Text><Text style={styles.body}>Für Fragen zur App, zum Datenschutz oder später zu Käufen wird vor Veröffentlichung eine öffentliche Support-Adresse hinterlegt.</Text><View style={styles.infoCard}><Text style={styles.infoTitle}>Kontakt-E-Mail</Text><Text style={styles.body}>[wird vor Veröffentlichung ergänzt]</Text></View></>;

 return <SafeAreaView style={styles.safe}><StatusBar style="dark"/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled">{body}</ScrollView></KeyboardAvoidingView><Menu/></SafeAreaView>;
}

function LegalRow({title,onPress}){return <Pressable onPress={onPress} style={styles.legalRow}><Text style={styles.legalRowText}>{title}</Text><Text style={styles.chev}>›</Text></Pressable>}
function LegalText({title,children}){return <View style={styles.legalText}><Text style={styles.infoTitle}>{title}</Text><Text style={styles.body}>{children}</Text></View>}

const styles=StyleSheet.create({
 safe:{flex:1,backgroundColor:C.bg},page:{paddingHorizontal:22,paddingTop:14,paddingBottom:64,maxWidth:720,width:'100%',alignSelf:'center'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},brand:{fontSize:14,letterSpacing:4,color:C.text,fontWeight:'600'},headerRight:{flexDirection:'row',alignItems:'center',gap:10},count:{fontSize:12,color:C.muted},menuButton:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},menuGlyph:{fontSize:19,color:C.text,marginTop:-2},track:{height:3,backgroundColor:C.line,borderRadius:20,overflow:'hidden',marginBottom:34},fill:{height:3,backgroundColor:C.green},
 homeTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},homeHero:{fontSize:39,lineHeight:45,color:C.text,fontWeight:'500',letterSpacing:-.5,marginBottom:18},quickGrid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:28},quickCard:{width:'48%',minHeight:116,borderWidth:1,borderColor:C.line,borderRadius:18,padding:15,backgroundColor:'rgba(255,255,255,.32)'},quickKicker:{fontSize:9,letterSpacing:1.2,color:C.muted,fontWeight:'600',marginBottom:8},quickTitle:{fontSize:17,color:C.text,fontWeight:'500'},quickArrow:{fontSize:22,color:C.green,marginTop:'auto',alignSelf:'flex-end'},hero:{fontSize:34,lineHeight:41,color:C.text,fontWeight:'500',marginBottom:18},title:{fontSize:27,lineHeight:34,color:C.text,fontWeight:'500',marginBottom:14},body:{fontSize:17,lineHeight:27,color:C.text},paragraph:{marginTop:14},eyebrow:{fontSize:11,letterSpacing:2,color:C.muted,fontWeight:'600',marginBottom:12},
 input:{minHeight:150,borderWidth:1,borderColor:C.line,borderRadius:16,padding:16,fontSize:17,lineHeight:25,color:C.text,backgroundColor:'rgba(255,255,255,.36)',marginTop:20},button:{backgroundColor:C.green,borderRadius:16,paddingVertical:16,paddingHorizontal:18,alignItems:'center',marginTop:24,borderWidth:1,borderColor:C.green},buttonOutline:{backgroundColor:'transparent'},buttonText:{fontSize:16,color:C.white,fontWeight:'600'},msg:{fontSize:14,lineHeight:21,color:C.muted,marginTop:14},
 scene:{borderWidth:1,borderColor:C.line,borderRadius:26,padding:22,backgroundColor:C.card},landscape:{height:155,borderRadius:22,overflow:'hidden',backgroundColor:C.sky,marginBottom:26,position:'relative'},landscapeLarge:{height:310,marginTop:4,marginBottom:38},landscapeImage:{...StyleSheet.absoluteFillObject,width:'100%',height:'100%'},landscapeVeil:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(226,232,226,.16)'},
 review:{borderWidth:1,borderColor:C.line,borderRadius:14,padding:15},reviewLabel:{fontSize:11,color:C.muted,marginBottom:5,textTransform:'uppercase',letterSpacing:1.2},card:{backgroundColor:C.card,borderRadius:18,padding:18,marginTop:14},label:{fontSize:16,lineHeight:24,color:C.text,fontWeight:'600',marginTop:24},homeLinks:{flexDirection:'row',justifyContent:'space-between',marginTop:24,gap:20},textLink:{fontSize:14,color:C.green,textDecorationLine:'underline'},
 menuOverlay:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(25,39,34,.34)',zIndex:20,alignItems:'flex-end'},menuPanel:{width:'88%',maxWidth:430,height:'100%',backgroundColor:C.bg,paddingHorizontal:24,paddingTop:18,paddingBottom:24},menuHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},closeButton:{width:44,height:44,alignItems:'center',justifyContent:'center'},closeGlyph:{fontSize:36,fontWeight:'200',color:C.text},menuTitle:{fontSize:34,lineHeight:41,color:C.text,fontWeight:'500',marginTop:42,marginBottom:22},menuRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:19,borderBottomWidth:1,borderBottomColor:C.line},menuRowText:{fontSize:18,color:C.text},chev:{fontSize:28,color:C.muted,fontWeight:'300'},menuFoot:{marginTop:'auto',paddingTop:28},small:{fontSize:13,lineHeight:20,color:C.muted},
 infoCard:{backgroundColor:C.card,borderRadius:18,padding:18,marginTop:14},infoTitle:{fontSize:16,lineHeight:23,color:C.text,fontWeight:'600',marginBottom:7},dangerRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:20,borderBottomWidth:1,borderBottomColor:C.line,marginBottom:18},dangerText:{fontSize:17,color:'#8A433B'},legalRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:21,borderBottomWidth:1,borderBottomColor:C.line},legalRowText:{fontSize:18,color:C.text},note:{marginTop:28,padding:16,borderRadius:14,borderWidth:1,borderColor:C.line},legalText:{marginBottom:26},warning:{fontSize:12,lineHeight:19,color:C.muted,borderTopWidth:1,borderTopColor:C.line,paddingTop:18,marginTop:10}
});
